### ISSUE TITLE
[feature] Cygwin support

### ISSUE THREAD

**Issue by op7ic** [EbryxLabs/Excavator#1]
Hi Guys, 

great tool. It would be useful to have it working on cygwin too. Default windows works just fine but paths etc gets messed up when using Cygwin

**Comment by RogueContact** [comment]
I'll be adding Cygwin support too.

From what I understand, you are facing the issue because of the `%4` or space between some words in the log file names. A quick and dirty solution to paths getting messed up is;
Move to the directory where the event log files are and then rename all of them to remove the `%4` and ` ` from the names using following PowerShell commandlets
- `get-childitem *.evtx | foreach { rename-item $_ $_.Name.Replace("%4", "") }`
- `get-childitem *.evtx | foreach { rename-item $_ $_.Name.Replace(" ", "") }`

> Hi Guys,
> 
> great tool. It would be useful to have it working on cygwin too. Default windows works just fine but paths etc gets messed up when using Cygwin

**Comment by RogueContact** [comment]
I'll be adding Cygwin support too.

From what I understand, you are facing the issue because of the %4 or space between some words in the log file names. A quick and dirty solution to paths getting messed up is;
Move to the directory where the event log files are and then rename all of them to remove the %4 and space from the names using following PowerShell commandlets

- get-childitem *.evtx | foreach { rename-item $_ $_.Name.Replace("%4", "") }
- get-childitem *.evtx | foreach { rename-item $_ $_.Name.Replace(" ", "") }

> Hi Guys,
> 
> great tool. It would be useful to have it working on cygwin too. Default windows works just fine but paths etc gets messed up when using Cygwin

**Comment by RogueContact** [comment]
Hi @op7ic ,

This repo has been moved [here](https://github.com/EbryxLabs/__DFIR-scripts/tree/master/Excavator). You can open this issue there as it will be maintained under that repo from now onwards.

Closing this one now.
